CREATE TABLE IF NOT EXISTS b_message(
	_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
	b_system_id INTEGER,
	b_sync BOOLEAN DEFAULT 0,
	b_type INTEGER NOT NULL,
	b_status INTEGER NOT NULL,
	b_from INTEGER,
	b_to INTEGER,
	b_size REAL NOT NULL,
	b_time DATETIME NOT NULL DEFAULT NOW(),
	b_data BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS b_phonebook(
	_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
	b_user_id INTEGER NOT NULL,
	b_name VARCHAR(128) NOT NULL,
	b_email VARCHAR(128) NOT NULL,
	b_operator BOOLEAN DEFAULT 0,
	b_walkie BOOLEAN DEFAULT 0,
	b_sim_phone VARCHAR(128),
	b_aux_phone1 VARCHAR(128),
	b_aux_phone2 VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS b_location(
	_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
	b_time DATETIME NOT NULL DEFAULT NOW(),
	b_lat DOUBLE,
	b_lon DOUBLE,
	b_alt DOUBLE,
	b_speed DOUBLE
);

CREATE TABLE IF NOT EXISTS b_event(
	_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
	b_time DATETIME NOT NULL DEFAULT NOW(),
	b_event INTEGER
);

CREATE TABLE IF NOT EXISTS b_stream(
	_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
	b_type INTEGER NOT NULL,
	b_value INTEGER NOT NULL,
	b_time DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS b_settings(
	b_user_id INTEGER,
	b_user_name VARCHAR(128),
	b_user_email VARCHAR(128),
	b_user_operator BOOLEAN DEFAULT 0,
	b_real_time_track BOOLEAN DEFAULT 0,
	b_connect_timeout INTEGER,
	b_inbound_bytes_limit INTEGER,
	b_outbound_bytes_limit INTEGER,
	b_inbound_bytes INTEGER,
	b_outbound_bytes INTEGER,
	b_speed_margin INTEGER,
	b_wait_margin INTEGER
);

INSERT INTO b_settings(b_user_id, b_user_name, b_user_email, b_user_operator, b_real_time_track, b_connect_timeout, b_inbound_bytes_limit, b_outbound_bytes_limit, b_inbound_bytes, b_outbound_bytes)
	VALUES(-1, '', '', FALSE, FALSE, -1, 0, 0, 0, 0);